ARDUINO_DIR   = /usr/share/arduino
ARDUINO_PORT  = /dev/ttyUSB0

USER_LIB_PATH = /home/openhabian/sketchbook/libraries
BOARD_TAG     = uno
ARDUINO_LIBS  = P1P2Serial

include /usr/share/arduino/Arduino.mk
